name: Package Neovim (Nightly)

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  package_linux:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-gnu
            use_qemu: false
            use_alpine: false
          - target: x86_64-unknown-linux-musl
            use_qemu: false
            use_alpine: true
          - target: aarch64-unknown-linux-gnu
            use_qemu: true
            use_alpine: false
          - target: aarch64-unknown-linux-musl
            use_qemu: true
            use_alpine: true
    runs-on: ubuntu-22.04

    steps:
      - name: Install requirements
        run: sudo apt-get install ninja-build gettext cmake unzip curl p7zip-full build-essential
      - uses: actions/checkout@v4
      - name: Clone Neovim
        run: |
          cd repos
          git clone https://github.com/neovim/neovim
      - name: Build Neovim
        run: |
          mkdir -p package/artifacts/nvim
          cd repos/neovim
          make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=../../package/artifacts/nvim

      - name: Package
        run: |
          cd package/artifacts
          7z a -mx=9 neovim-statiolake-${{ matrix.target }}.zip nvim

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: neovim-statiolake-${{ matrix.target }}
          path: ./package/artifacts/neovim-statiolake-${{ matrix.target }}.zip

  package_windows:
    env:
      NEOVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip
      NEOVIMQT_REPO: https://github.com/equalsraf/Neovim-qt
      NEOVIMQT_PATCHREPO: https://github.com/statiolake/Neovim-qt
      NEOVIMQT_PATCHREVS: win10-darkmode enlarge clip-undercurl fix-ime-position
      VCVARSALL: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
      GITBIN: C:\Program Files\Git\usr\bin
      QT_VERSION: 5.15.2
    runs-on: windows-2019
    steps:
      - name: Initalize
        id: init
        shell: bash
        run: |
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - name: Download Neovim nightly
        id: neovim_download
        shell: bash
        run: |
          curl -f -L ${NEOVIM_DOWNLOAD_URL} -o downloads/nvim-win64.zip
          mkdir package/artifacts
          7z x -y downloads/nvim-win64.zip -opackage/artifacts

          mv package/artifacts/nvim-win64 package/artifacts/Neovim
          package/artifacts/Neovim/bin/nvim --version
          delim="$(openssl rand -hex 8)"
          echo "version<<${delim}" >> $GITHUB_OUTPUT
          package/artifacts/Neovim/bin/nvim --version >> $GITHUB_OUTPUT
          echo "${delim}" >> $GITHUB_OUTPUT

      - name: Clone Neovim-qt
        shell: bash
        run: |
          cd repos
          git clone ${NEOVIMQT_REPO}
          cd Neovim-qt

          # add patch repo
          git remote add statiolake ${NEOVIMQT_PATCHREPO}
          git fetch statiolake

      - name: Apply private patches for Neovim-qt
        shell: bash
        run: |
          cd repos/Neovim-qt
          git config --local user.name "statiolake"
          git config --local user.email "statiolake@users.noreply.github.com"
          for patch in ${NEOVIMQT_PATCHREVS}; do
            git checkout -b $patch statiolake/$patch
            git rebase origin/master
            git checkout master
            git merge --squash $patch
            git commit -m "Apply private patch: merge branch ${patch}"
          done

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1 # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache-${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          arch: win64_msvc2019_64
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build Neovim-qt
        shell: cmd
        run: |
          path %PATH%;%CD%\package\artifacts\Neovim\bin
          call "%VCVARSALL%" x64
          cd repos\Neovim-qt
          md build INSTALL
          cd build

          echo Prepare...
          cmake -G "Visual Studio 16" ^
            -DCMAKE_PREFIX_PATH="%QT5_Dir%\msvc2019_64" ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_INSTALL_PREFIX=..\INSTALL ..

          echo Build...
          cmake --build . --target install --config Release

      - name: Install Neovim-qt
        shell: cmd
        run: |
          robocopy repos\Neovim-qt\INSTALL package\artifacts\Neovim /E /IS
          :: Ignore robocopy return value (that is not error actually)
          echo robocopy finished at %ERRORLEVEL% - assume success
          exit 0

      - name: Package
        shell: cmd
        run: |
          cd package\artifacts
          7z a -mx=9 neovim-statiolake-x86_64-pc-windows-msvc.zip Neovim

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: neovim-statiolake-x86_64-pc-windows-msvc
          path: ./package/artifacts/neovim-statiolake-x86_64-pc-windows-msvc.zip

  release:
    runs-on: windows-latest
    needs: [package_windows, package_linux]
    if: github.event_name != 'pull_request'

    steps:
      - name: Initalize
        shell: bash
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: neovim-statiolake
      - name: Get version
        id: version
        shell: bash
        run: |
          neovim-statiolake/Neovim/bin/nvim --version | tee version.txt
          echo "short=$(neovim-statiolake/Neovim/bin/nvim --version | head -n 1 | sed -E 's/^NVIM //')" >> $GITHUB_OUTPUT
          delim="$(openssl rand -hex 8)"
          echo "long<<${delim}" >> $GITHUB_OUTPUT
          neovim-statiolake/Neovim/bin/nvim --version >> $GITHUB_OUTPUT
          echo "${delim}" >> $GITHUB_OUTPUT
      - name: Commit
        id: commit
        shell: bash
        run: |
          if git diff --quiet HEAD version.txt; then
            echo "No update - ignore publishing"
            echo "skipped=yes" >> $GITHUB_OUTPUT
          else
            git config --local user.name "statiolake"
            git config --local user.email "statiolake@users.noreply.github.com"
            git add version.txt
            git commit -m "${{ steps.version.outputs.short }}"
            git tag "${{ steps.version.outputs.short }}"
            git push origin master --tags
            echo "skipped=no" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@9993ae85344fa542b3edb2533f97011277698cf6
        if: steps.commit.outputs.skipped == 'no'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.version.outputs.short }}
          body: |
            ${{ steps.version.outputs.long }}
          tag_name: ${{ steps.version.outputs.short }}
          draft: false
          prerelease: false
          files: |
            ./neovim-statiolake/neovim-statiolake.zip
            ./neovim-statiolake/neovim-statiolake.7z
